### PR TITLE
add RepoQuery and AddCommentMutation

### PR DESCRIPTION
**Pull request by nrbnlulu**
Hello this is me
### What is that headerfdsfds

### CODE REVIEW

**Comment by nrbnlulu** [comment]
This is a comment

**Comment by nrbnlulu** [comment]
Thats a comment

**Comment by nrbnlulu** [comment]
another comment

**Comment by nrbnlulu** [comment]
fdsaafsdaf

**Comment by nrbnlulu** [comment]
rerender

**Comment by nrbnlulu** [comment]
That's two cats
cat
cat2

**Comment by nrbnlulu** [comment]
nere msd

**Comment by AlmogZinger** [comment]
test

**Pull request merged**
